# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c606a34e96b3608344b8e3286b569db0ed77a8245866bafacb43ebf72b347ab113e686848ef4f80bfcb4e78e80a93cc300da6d9c21ba1ca372b44141d7e9794a

test:
  secret_key_base: 0cf1e515bc74be3e8a5cbfbbb1f2d43c563b85606950fa7b1c243f7d976a28285372fb053246d7713d6b1fb9df787cf592e8243017633689ad1410bb656a05d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
